<?php

/**
 * @file
 * Contains custom_events.module.
 */

use Drupal\cdp_profile\Event\UserLoginEvent;

/**
 * Implements hook_user_login().
 */
function cdp_profile_user_login($account) {
  // Instantiate our event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(UserLoginEvent::EVENT_NAME, $event);
}

function cdp_profile_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if (\Drupal::currentUser()
      ->isAuthenticated() && \Drupal::routeMatch()->getRouteName() ==='cdp_profile.page') {
    $suggestions[] = $hook . '__' . 'profile';
  }
}

  function cdp_profile_entity_view_mode_alter(&$view_mode){
    $entity     = \Drupal::entityTypeManager()->getStorage('user')->load(1);
    $entityType = 'user';
    //    $display = entity_get_display($entityType, $node->getType(), $viewmode);
    $viewBuilder = \Drupal::entityTypeManager()->getViewBuilder($entityType);


    $view_mode = 'user.profilepage';
    dump($viewBuilder->view($entity)['#view_mode']);
//  dump($view_mode);


//  die();
  }
function cdp_profile_view_entity_type_alter(array &$entity_types) {

  die();

}